"""add disabled_at to short_urls (brownfield)

Revision ID: 7386e8754937
Revises: eb344d5c06b2
Create Date: 2026-08-04 13:02:13.096848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7386e8754937'
down_revision: Union[str, Sequence[str], None] = 'eb344d5c06b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_urls', sa.Column('disabled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_urls', 'disabled_at')
    # ### end Alembic commands ###
