"""create short_urls and click_events tables

Revision ID: 89716978921e
Revises: 
Create Date: 2026-08-03 21:50:33.652149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89716978921e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_code', sa.String(length=32), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creating_workflow_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_urls_short_code'), 'short_urls', ['short_code'], unique=True)
    op.create_table('click_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_url_id', sa.Integer(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('referrer_domain', sa.String(length=255), nullable=True),
    sa.Column('user_agent_category', sa.String(length=16), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['short_url_id'], ['short_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click_events')
    op.drop_index(op.f('ix_short_urls_short_code'), table_name='short_urls')
    op.drop_table('short_urls')
    # ### end Alembic commands ###
